### ISSUE TITLE
Not getting installed with Python 3.10

### ISSUE THREAD

**Issue by NIkhilbadveli** [rajcscw/nlp-gym#8]
Hi, I am trying install this package in Python 3.10 and it's throwing error.

`running build_ext
    /bin/sh: 1: pkg-config: not found
    mkdir: cannot create directory ‘bundled’: File exists
    fatal: destination path 'sentencepiece' already exists and is not an empty directory.
    fatal: destination path 'sentencepiece' already exists and is not an empty directory.
    mkdir: cannot create directory ‘build’: File exists
    ./build_bundled.sh: 15: cmake: not found
    make: *** No targets specified and no makefile found. Stop.
    make: *** No rule to make target 'install'. Stop.
    env: ‘pkg-config’: No such file or directory
    Failed to find sentencepiece pkg-config`

Please help me fix this. I don't want to downgrade my Python version.

**Comment by rajcscw** [comment]
Sorry for the late response. Is it still a problem?

**Comment by NIkhilbadveli** [comment]
Yes, it is working with Python 3.7.

**Comment by rajcscw** [comment]
Ok good to know. I have not tested with 3.10 though.
